version: '3.4'

x-common-args: &common-args
  PYTHON_VERSION: ${PYTHON_VERSION}
  CONAN_VERSION: ${CONAN_VERSION}
  DOCKER_USERNAME: ${DOCKER_USERNAME}
  DOCKER_TAG: ${DOCKER_TAG}
  DISTRO: ${DISTRO}
  DISTRO_VERSION: ${DISTRO_VERSION}

services:
  gcc10: &gcc10
    platform: ${PLATFORM}
    image: ${DOCKER_USERNAME}/gcc10-${DISTRO}${DISTRO_VERSION}:latest
    container_name: gcc10
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DOCKER_USERNAME}/gcc10-${DISTRO}${DISTRO_VERSION}:latest
        - ${DOCKER_USERNAME}/gcc10-${DISTRO}${DISTRO_VERSION}:${DOCKER_TAG}
      args:
        <<: *common-args
        COMPILER: gcc
        COMPILER_VERSION: 10
    tty: true

  gcc11: &gcc11
    platform: ${PLATFORM}
    image: ${DOCKER_USERNAME}/gcc11-${DISTRO}${DISTRO_VERSION}:latest
    container_name: gcc11
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DOCKER_USERNAME}/gcc11-${DISTRO}${DISTRO_VERSION}:latest
        - ${DOCKER_USERNAME}/gcc11-${DISTRO}${DISTRO_VERSION}:${DOCKER_TAG}
      args:
        <<: *common-args
        COMPILER: gcc
        COMPILER_VERSION: 11
    tty: true

  gcc12: &gcc12
    platform: ${PLATFORM}
    image: ${DOCKER_USERNAME}/gcc12-${DISTRO}${DISTRO_VERSION}:latest
    container_name: gcc12
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DOCKER_USERNAME}/gcc12-${DISTRO}${DISTRO_VERSION}:latest
        - ${DOCKER_USERNAME}/gcc12-${DISTRO}${DISTRO_VERSION}:${DOCKER_TAG}
      args:
        <<: *common-args
        COMPILER: gcc
        COMPILER_VERSION: 12
    tty: true

  clang12: &clang12
    platform: ${PLATFORM}
    image: ${DOCKER_USERNAME}/clang12-${DISTRO}${DISTRO_VERSION}:latest
    container_name: clang12
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DOCKER_USERNAME}/clang12-${DISTRO}${DISTRO_VERSION}:latest
        - ${DOCKER_USERNAME}/clang12-${DISTRO}${DISTRO_VERSION}:${DOCKER_TAG}
      args:
        <<: *common-args
        COMPILER: clang
        COMPILER_VERSION: 12
    tty: true

  clang13: &clang13
    platform: ${PLATFORM}
    image: ${DOCKER_USERNAME}/clang13-${DISTRO}${DISTRO_VERSION}:latest
    container_name: clang13
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DOCKER_USERNAME}/clang13-${DISTRO}${DISTRO_VERSION}:latest
        - ${DOCKER_USERNAME}/clang13-${DISTRO}${DISTRO_VERSION}:${DOCKER_TAG}
      args:
        <<: *common-args
        COMPILER: clang
        COMPILER_VERSION: 13
    tty: true

  clang14: &clang14
    platform: ${PLATFORM}
    image: ${DOCKER_USERNAME}/clang14-${DISTRO}${DISTRO_VERSION}:latest
    container_name: clang14
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${DOCKER_USERNAME}/clang14-${DISTRO}${DISTRO_VERSION}:latest
        - ${DOCKER_USERNAME}/clang14-${DISTRO}${DISTRO_VERSION}:${DOCKER_TAG}
      args:
        <<: *common-args
        COMPILER: clang
        COMPILER_VERSION: 14
    tty: true
